---
- name: Check ver
  hosts: all
  fork: 10
  become: 
  vars:
    ver_chrony: 3.4
    ver_nfs: 1.3.0
    ver_ldapc: 2.4.44
  tasks:
  - package_facts: {}
  - name: List chrony ver
    debug:
      msg: "chrony: {{ ansible_facts.packages['chrony'][0].version }}"
    when: ansible_facts.packages['chrony'][0].version != "3.4"
  - name: List nfs-utils ver
    debug:
      msg: "nfs: {{ ansible_facts.packages['nfs-utils'][0].version }}"
    when: ansible_facts.packages['nfs-utils'][0].version != "{{ ver_nfs }}"
  - name: List openldap ver
    debug:
      msg: ldap client: {{ ansible_facts.packages['openldap-clients'][0].version }}"
    when: ansible_facts.packages['openldap-clients'][0].version != "{{ ver_ldapc 
