---
- name: conf DNS
  hosts: ldap01
  roles: slapd
  vars:
    ldap_schemas:
      - cosine
        inetorgperson
    ldap_replication_consumer: false
    ldap_domain: scnu.edu
    ldap_domain_ex: cn
    ldap_suffix: o=od
    ldap_admin_password: 123456
    ldap_replication_provider: false
